//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdutoFornecedor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fornecedor
    {
        public int IdFornecedor { get; set; }
        public string Nome_Fornecedor { get; set; }
        public string CNPJ { get; set; }
        public string Endereco { get; set; }
        public bool Ativo { get; set; }
    }
}
